# Generated by Django 5.1.4 on 2026-05-09 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('timezone_name', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ad_accounts',
            },
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('optimization_goal', models.CharField(blank=True, max_length=50)),
                ('billing_event', models.CharField(blank=True, max_length=50)),
                ('ai_decision', models.CharField(blank=True, max_length=10)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'adsets',
            },
        ),
        migrations.CreateModel(
            name='AdInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('campaign', 'Campaign'), ('adset', 'AdSet'), ('ad', 'Ad')], default='adset', max_length=10)),
                ('entity_id', models.CharField(db_index=True, max_length=50)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('reach', models.PositiveBigIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roas', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ad_insights',
                'ordering': ['-date'],
                'unique_together': {('entity_id', 'level', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('creative_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='meta_ads.adset')),
            ],
            options={
                'db_table': 'ads',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('objective', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DELETED', 'Deleted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='meta_ads.adaccount')),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.AddField(
            model_name='adset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='meta_ads.campaign'),
        ),
    ]
