# Generated by Django 5.1.4 on 2026-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinsight',
            name='frequency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='adset',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adset',
            name='ai_decision',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
