# Generated by Django 5.1.4 on 2026-05-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0003_ad_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='promoted_post_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
