# Generated by Django 5.1.4 on 2026-05-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0004_ad_promoted_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinsight',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adinsight',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
