# Generated by Django 5.1.4 on 2026-05-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(choices=[('cpa', 'Cost Per Action'), ('roas', 'ROAS'), ('ctr', 'CTR'), ('spend', 'Spend'), ('cpc', 'CPC')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal')], max_length=5)),
                ('threshold', models.FloatField()),
                ('action', models.CharField(choices=[('PAUSE', 'Pause AdSet'), ('SCALE_BUDGET', 'Scale Budget'), ('ALERT', 'Send Alert')], max_length=20)),
                ('scale_factor', models.FloatField(default=1.5, help_text='Multiply budget by this when SCALE_BUDGET')),
                ('lookback_days', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'automation_rules',
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(db_index=True, max_length=50)),
                ('adset_name', models.CharField(blank=True, max_length=255)),
                ('trigger_source', models.CharField(choices=[('RULE', 'Rule Engine'), ('AI', 'AI Decision'), ('ANOMALY', 'Anomaly Detection'), ('MANUAL', 'Manual Trigger')], max_length=10)),
                ('action_taken', models.CharField(max_length=50)),
                ('ai_decision', models.CharField(blank=True, max_length=10)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('metric_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations.automationrule')),
            ],
            options={
                'db_table': 'automation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
