# Generated by Django 5.1.4 on 2026-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_ads', '0002_adinsight_frequency_adset_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='ai_decision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='ai_reasoning',
            field=models.TextField(blank=True),
        ),
    ]
