# Generated by Django 5.1.4 on 2026-05-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100, unique=True)),
                ('post_id', models.CharField(db_index=True, max_length=100)),
                ('adset_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('ad_id', models.CharField(blank=True, max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_qualified', models.BooleanField(default=False)),
                ('commented_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='messenger.facebookpage')),
            ],
            options={
                'db_table': 'page_comments',
                'ordering': ['-commented_at'],
            },
        ),
    ]
