# Generated by Django 5.1.4 on 2026-05-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_leadscore_deep_funnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.CharField(blank=True, max_length=30)),
                ('service', models.TextField(blank=True)),
                ('raw_message', models.TextField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Đã đặt lịch'), ('COMPLETED', 'Đã thực hiện'), ('CANCELLED', 'Đã huỷ')], default='SCHEDULED', max_length=15)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='messenger.conversation')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.facebookpage')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-detected_at'],
            },
        ),
    ]
