# Generated by Django 5.1.4 on 2026-05-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('page_access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='meta_ads.adaccount')),
            ],
            options={
                'db_table': 'fb_pages',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('psid', models.CharField(db_index=True, max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('referral_ad_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('referral_adset_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('referral_campaign_id', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('is_qualified', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('WEBHOOK', 'Webhook (real-time)'), ('POLLING', 'API Polling')], default='WEBHOOK', max_length=10)),
                ('first_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messenger.facebookpage')),
            ],
            options={
                'db_table': 'messenger_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('intent_level', models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], default='COLD', max_length=10)),
                ('ai_summary', models.TextField(blank=True)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_budget_signal', models.BooleanField(default=False)),
                ('has_urgency_signal', models.BooleanField(default=False)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_score', to='messenger.conversation')),
            ],
            options={
                'db_table': 'lead_scores',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('IN', 'From User'), ('OUT', 'From Page')], max_length=3)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.conversation')),
            ],
            options={
                'db_table': 'messenger_messages',
                'ordering': ['sent_at'],
            },
        ),
    ]
